# Generated by Django 2.2.7 on 2019-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20191213_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drip', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
