# Generated by Django 2.2.7 on 2019-11-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bench',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='deadlift',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfme',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='squat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
