# Generated by Django 2.2.7 on 2019-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191127_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='perpose',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
